app = "keegan-ingest"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  MTX_LOGLEVEL = "info"

[[services]]
  internal_port = 1935
  protocol = "tcp"
  [[services.ports]]
    port = 1935

[[services]]
  internal_port = 8888
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

[[services]]
  internal_port = 8889
  protocol = "tcp"
  [[services.ports]]
    port = 8889

[[services]]
  internal_port = 8000
  protocol = "udp"
  [[services.ports]]
    port = 8000
